package com.iperf3.android.domain.util

import com.iperf3.android.domain.model.TestResult

object ReportGenerator {

    fun generateTextReport(result: TestResult): String = buildString {
        appendLine("═══════════════════════════════════════")
        appendLine("       iPerf3 Network Test Report")
        appendLine("═══════════════════════════════════════")
        appendLine()
        appendLine("Date:       ${result.formatTimestamp("yyyy-MM-dd HH:mm:ss")}")
        appendLine("Server:     ${result.serverHost}:${result.serverPort}")
        appendLine("Protocol:   ${result.protocol}")
        appendLine("Mode:       ${result.modeDescription}")
        appendLine("Streams:    ${result.numStreams}")
        appendLine("Duration:   ${String.format("%.1f", result.durationSeconds)}s")
        appendLine()
        appendLine("─── Bandwidth ───────────────────────")
        appendLine("  Average:  ${result.formatAvgBandwidth()}")
        appendLine("  Minimum:  ${formatBps(result.minBandwidth)}")
        appendLine("  Maximum:  ${formatBps(result.maxBandwidth)}")
        appendLine()
        appendLine("─── Transfer ────────────────────────")
        appendLine("  Data:     ${result.formatDataTransferred()}")
        appendLine()

        if (result.isUdp) {
            appendLine("─── UDP Metrics ─────────────────────")
            result.jitter?.let {
                appendLine("  Jitter:       ${String.format("%.3f", it)} ms")
            }
            result.packetLoss?.let {
                appendLine("  Packet Loss:  ${String.format("%.2f", it)}%")
            }
            result.totalPackets?.let { total ->
                result.lostPackets?.let { lost ->
                    appendLine("  Packets:      $lost lost / $total total")
                }
            }
            appendLine()
        }

        if (result.isTcp && result.retransmits != null) {
            appendLine("─── TCP Metrics ─────────────────────")
            appendLine("  Retransmits:  ${result.retransmits}")
            appendLine()
        }

        appendLine("─── Quality ─────────────────────────")
        appendLine("  Score:    ${String.format("%.0f", result.qualityScore)} / 100 (${result.qualityDescription()})")
        appendLine()
        appendLine("═══════════════════════════════════════")
        appendLine("  Generated by iPerf3 for Android")
        appendLine("═══════════════════════════════════════")
    }

    fun generateCsvRow(result: TestResult): String {
        return listOf(
            result.formatTimestamp("yyyy-MM-dd HH:mm:ss"),
            result.serverHost,
            result.serverPort.toString(),
            result.protocol,
            result.modeDescription,
            String.format("%.2f", result.avgMbps),
            String.format("%.2f", result.minBandwidth / 1_000_000),
            String.format("%.2f", result.maxBandwidth / 1_000_000),
            result.jitter?.let { String.format("%.3f", it) } ?: "",
            result.packetLoss?.let { String.format("%.2f", it) } ?: "",
            result.retransmits?.toString() ?: "",
            String.format("%.0f", result.qualityScore),
            String.format("%.1f", result.durationSeconds),
            result.formatDataTransferred()
        ).joinToString(",")
    }

    fun csvHeader(): String {
        return "Date,Server,Port,Protocol,Mode,Avg Mbps,Min Mbps,Max Mbps,Jitter ms,Loss %,Retransmits,Quality,Duration s,Data"
    }

    fun generateCsvReport(results: List<TestResult>): String = buildString {
        appendLine(csvHeader())
        results.forEach { appendLine(generateCsvRow(it)) }
    }

    private fun formatBps(bps: Double): String {
        return when {
            bps >= 1_000_000_000 -> String.format("%.2f Gbps", bps / 1_000_000_000)
            bps >= 1_000_000 -> String.format("%.2f Mbps", bps / 1_000_000)
            bps >= 1_000 -> String.format("%.2f Kbps", bps / 1_000)
            else -> String.format("%.0f bps", bps)
        }
    }
}
